### ISSUE TITLE
Main methods are everywhere!

### ISSUE THREAD

**Issue by jacksonblankenship** [Get-Reqd/CACI-Utility#11]
We need to get rid all main methods being used outside of the Driver class. Remove all unnecessary main methods outside of the Driver class and replace them with constructors if need be. Be sure to make sure nothing breaks because of these changes.

This is a main method:
```Java
class ExampleClass {

   public static void main(String[] args) {

      // Code here

   }
}
```

These should only be used in the **main class that runs the program** (Driver.java). If you need to set up your class for whatever reason, use a constructor instead. When you create an object, the constructor will be run automatically, effectively doing what I think was intended with all of these main methods being used.

Constructor:

```Java
class ExampleClass {

   public ExampleClass() {

      // Code here

   }
}
```

**Comment by jacksblan** [comment]
public static void main(String[] args) is a main method btw.

**Comment by justaviet** [comment]
That would be my bad! haha
Thanks for the theory refresher.
I only did that because I needed a quick and dirty way to test a class independently.
I'll keep that in mind for the future.

**Comment by jacksonblankenship** [comment]
No problem @jv405
