### ISSUE TITLE
Output Directory Path

### ISSUE THREAD

**Issue by HannahWinslow** [Get-Reqd/CACI-Utility#14]
This may be resolved in issue #4 , but if not:

Issue: After selecting a directory for the output path, the last folder level is taken away.

Directions to demonstrate the issue:
1) Run the program
2) In the output section, click "browse"
3)  Browse to desired folder
4) Hit "select" 
5) Notice the directory path is one level shorter than you selected

Goal: The whole path to the selected folder should appear.

**Comment by HannahWinslow** [comment]
I'll do this if Minh hasn't already

**Comment by HannahWinslow** [comment]
@jacksblan This issue can be closed. Just updated my code and it's working. Someone else must have fixed it. getCurrentDirectory() changed to getSelectedFile() solved it

**Comment by jacksonblankenship** [comment]
@HannahWinslow Thanks Hannah!
