### ISSUE TITLE
Checksum implementation for Split/Assemble

### ISSUE THREAD

**Issue by jacksonblankenship** [Get-Reqd/CACI-Utility#5]
The checksum logic was lost in transition. The original code was bugging out with our current chnages anyway so this is a good opportunity for us to get on top of this. Since Split.java and Assemble.java don't seem to be doing anything right now, it may be better to create a Checksum class that can be called from FileSplitter.java.

**Comment by noahHetrick** [comment]
yeah you can put me on this
